service: lambda-print

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11

functions:
  printable:
    handler: handler.printable
    events:
      - sqs:
          arn:
            Fn::ImportValue: MyQueueArn

custom:
  localstack:
    stages:
      - local

plugins:
  - serverless-python-requirements
  - serverless-localstack
